/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import BackGround.MemberDAO;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CarpDm
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        tableRefresh_MemberTable();
        tableRefresh_MsfTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTabbedPane = new javax.swing.JTabbedPane();
        Panel_PayManager = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Tf_Date = new javax.swing.JTextField();
        Tf_Price = new javax.swing.JTextField();
        Tf_Event = new javax.swing.JTextField();
        Tf_Name = new javax.swing.JTextField();
        Tf_Payment = new javax.swing.JTextField();
        Tf_Remarks = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        MsfTable = new javax.swing.JTable();
        FrameCall_Calander = new javax.swing.JButton();
        Btn_Enter_Mfs = new javax.swing.JButton();
        Btn_Reset_Mfs = new javax.swing.JButton();
        Btn_Update_Mfs = new javax.swing.JButton();
        Btn_Delete_Mfs = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Tf_Index = new javax.swing.JTextField();
        FrameCall_Member = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Tf_AllMoney = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Tf_PresentMoney = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Tf_NotPaymoney = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        CB_Sort = new javax.swing.JComboBox<>();
        Panel_MemberManager = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MemberTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        TF_StudentId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Tf_Department = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Tf_Name_Mem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Tf_Phone = new javax.swing.JTextField();
        Btn_Enter_Mem = new javax.swing.JButton();
        Btn_Update_Mem = new javax.swing.JButton();
        Btn_Delete_Mem = new javax.swing.JButton();
        Btn_Reset_Mem = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        TF_OldStudent = new javax.swing.JTextField();
        TF_NewStudent = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        TF_AllStudent = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Panel_EventManager = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        EventTable = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        TF_EventDate = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        TF_EventName = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        TF_AverageMoney = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("날      짜");

        jLabel2.setText("행      사");

        jLabel3.setText("금      액");

        jLabel4.setText("이      름");

        jLabel5.setText("납부금액");

        jLabel7.setText("비      고");

        Tf_Date.setEditable(false);
        Tf_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_DateActionPerformed(evt);
            }
        });

        Tf_Price.setText("행사 금액");
        Tf_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_PriceActionPerformed(evt);
            }
        });

        Tf_Event.setText("행사 입력");
        Tf_Event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_EventActionPerformed(evt);
            }
        });

        Tf_Name.setText("학생 이름");
        Tf_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_NameActionPerformed(evt);
            }
        });

        Tf_Payment.setText("납부 금액");
        Tf_Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_PaymentActionPerformed(evt);
            }
        });

        Tf_Remarks.setText("비고");
        Tf_Remarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_RemarksActionPerformed(evt);
            }
        });

        MsfTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "날짜", "이름", "행사", "금액", "납부금액", "미납금액", "비고"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MsfTable.getTableHeader().setResizingAllowed(false);
        MsfTable.getTableHeader().setReorderingAllowed(false);
        MsfTable.getTableHeader().setReorderingAllowed(false);
        MsfTable.getTableHeader().setResizingAllowed(false);
        jScrollPane4.setViewportView(MsfTable);

        FrameCall_Calander.setText("달력");
        FrameCall_Calander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrameCall_CalanderActionPerformed(evt);
            }
        });

        Btn_Enter_Mfs.setText("입력");

        Btn_Reset_Mfs.setText("초기화");

        Btn_Update_Mfs.setText("수정");

        Btn_Delete_Mfs.setText("삭제");

        jLabel11.setText("번      호");

        Tf_Index.setEditable(false);
        Tf_Index.setText("인덱스 번호");
        Tf_Index.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_IndexActionPerformed(evt);
            }
        });

        FrameCall_Member.setText("회원");

        jLabel12.setText("전체잔액");

        Tf_AllMoney.setEditable(false);
        Tf_AllMoney.setText("전체잔액");
        Tf_AllMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_AllMoneyActionPerformed(evt);
            }
        });

        jLabel17.setText("현재잔액");

        Tf_PresentMoney.setEditable(false);
        Tf_PresentMoney.setText("현재잔액");
        Tf_PresentMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_PresentMoneyActionPerformed(evt);
            }
        });

        jLabel19.setText("미납총액");

        Tf_NotPaymoney.setEditable(false);
        Tf_NotPaymoney.setText("미납총액");
        Tf_NotPaymoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_NotPaymoneyActionPerformed(evt);
            }
        });

        jLabel20.setText("정렬방법");

        CB_Sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_Sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_SortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_PayManagerLayout = new javax.swing.GroupLayout(Panel_PayManager);
        Panel_PayManager.setLayout(Panel_PayManagerLayout);
        Panel_PayManagerLayout.setHorizontalGroup(
            Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                        .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PayManagerLayout.createSequentialGroup()
                                .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tf_Remarks, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tf_Payment, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tf_Name, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tf_Price, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tf_Event))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FrameCall_Member))
                            .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                                .addComponent(Tf_Date)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FrameCall_Calander))))
                    .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                        .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tf_Index, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                                .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tf_NotPaymoney))
                                .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tf_PresentMoney))
                                .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tf_AllMoney)))
                            .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CB_Sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                                .addComponent(Btn_Enter_Mfs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Update_Mfs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Delete_Mfs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Reset_Mfs)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_PayManagerLayout.setVerticalGroup(
            Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                        .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_AllMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_PresentMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_NotPaymoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_Sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_Index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tf_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tf_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FrameCall_Member))
                                .addGap(18, 18, 18)
                                .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tf_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tf_Remarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Panel_PayManagerLayout.createSequentialGroup()
                                .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Tf_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FrameCall_Calander))
                                .addGap(18, 18, 18)
                                .addComponent(Tf_Event, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(Panel_PayManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Enter_Mfs)
                            .addComponent(Btn_Reset_Mfs)
                            .addComponent(Btn_Update_Mfs)
                            .addComponent(Btn_Delete_Mfs)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
                .addContainerGap())
        );

        JTabbedPane.addTab("회비관리", Panel_PayManager);
        Panel_PayManager.getAccessibleContext().setAccessibleName("회비관리");
        Panel_PayManager.getAccessibleContext().setAccessibleDescription("");

        MemberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "학번", "학과", "이름", "전화번호"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MemberTable.getTableHeader().setResizingAllowed(false);
        MemberTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(MemberTable);

        jLabel6.setText("학      번");

        TF_StudentId.setText("학번입력");
        TF_StudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_StudentIdActionPerformed(evt);
            }
        });

        jLabel8.setText("학      과");

        Tf_Department.setText("학과입력");
        Tf_Department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_DepartmentActionPerformed(evt);
            }
        });

        jLabel9.setText("이      름");

        Tf_Name_Mem.setText("이름입력");

        jLabel10.setText("전화번호");

        Tf_Phone.setText("전화번호");
        Tf_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_PhoneActionPerformed(evt);
            }
        });

        Btn_Enter_Mem.setText("입력");

        Btn_Update_Mem.setText("수정");

        Btn_Delete_Mem.setText("삭제");

        Btn_Reset_Mem.setText("초기화");

        jLabel21.setText("재 학 생");

        TF_OldStudent.setEditable(false);
        TF_OldStudent.setText("재학생 인원");
        TF_OldStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_OldStudentActionPerformed(evt);
            }
        });

        TF_NewStudent.setEditable(false);
        TF_NewStudent.setText("신입생 인원");
        TF_NewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_NewStudentActionPerformed(evt);
            }
        });

        jLabel22.setText("신 입 생");

        TF_AllStudent.setEditable(false);
        TF_AllStudent.setText("총인원");
        TF_AllStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_AllStudentActionPerformed(evt);
            }
        });

        jLabel23.setText("총     원");

        javax.swing.GroupLayout Panel_MemberManagerLayout = new javax.swing.GroupLayout(Panel_MemberManager);
        Panel_MemberManager.setLayout(Panel_MemberManagerLayout);
        Panel_MemberManagerLayout.setHorizontalGroup(
            Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MemberManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_MemberManagerLayout.createSequentialGroup()
                        .addComponent(Btn_Enter_Mem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Update_Mem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Delete_Mem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Reset_Mem))
                    .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_MemberManagerLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Tf_Department))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_MemberManagerLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TF_StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_MemberManagerLayout.createSequentialGroup()
                            .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Tf_Phone)
                                .addComponent(Tf_Name_Mem))))
                    .addGroup(Panel_MemberManagerLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_OldStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_MemberManagerLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_NewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_MemberManagerLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_AllStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_MemberManagerLayout.setVerticalGroup(
            Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MemberManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_MemberManagerLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_OldStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_NewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_AllStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_Name_Mem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(Panel_MemberManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Enter_Mem)
                    .addComponent(Btn_Reset_Mem)
                    .addComponent(Btn_Update_Mem)
                    .addComponent(Btn_Delete_Mem))
                .addGap(113, 113, 113))
        );

        JTabbedPane.addTab("회원관리", Panel_MemberManager);

        EventTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "날짜", "행사", "참여인원", "회비총액", "미납총액"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EventTable.getTableHeader().setResizingAllowed(false);
        EventTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(EventTable);

        jLabel24.setText("날      짜");

        TF_EventDate.setEditable(false);
        TF_EventDate.setText("행사 날짜");
        TF_EventDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_EventDateActionPerformed(evt);
            }
        });

        jLabel25.setText("행      사");

        TF_EventName.setEditable(false);
        TF_EventName.setText("행사 이름");
        TF_EventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_EventNameActionPerformed(evt);
            }
        });

        jLabel26.setText("평균회비 ");

        TF_AverageMoney.setEditable(false);
        TF_AverageMoney.setText("1인당 평균회비");
        TF_AverageMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_AverageMoneyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_EventManagerLayout = new javax.swing.GroupLayout(Panel_EventManager);
        Panel_EventManager.setLayout(Panel_EventManagerLayout);
        Panel_EventManagerLayout.setHorizontalGroup(
            Panel_EventManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EventManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel_EventManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_EventManagerLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF_EventDate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_EventManagerLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF_EventName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_EventManagerLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_AverageMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        Panel_EventManagerLayout.setVerticalGroup(
            Panel_EventManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EventManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Panel_EventManagerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Panel_EventManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_EventDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_EventManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_EventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_EventManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_AverageMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("행사관리", Panel_EventManager);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTabbedPane)
                .addContainerGap())
        );

        JTabbedPane.getAccessibleContext().setAccessibleName("");
        JTabbedPane.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tf_EventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_EventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_EventActionPerformed

    private void Tf_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_NameActionPerformed

    private void Tf_PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_PaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_PaymentActionPerformed

    private void Tf_RemarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_RemarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_RemarksActionPerformed

    private void Tf_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_DateActionPerformed

    private void TF_StudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_StudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_StudentIdActionPerformed

    private void Tf_DepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_DepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_DepartmentActionPerformed

    private void Tf_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_PhoneActionPerformed

    private void Tf_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_PriceActionPerformed

    private void FrameCall_CalanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrameCall_CalanderActionPerformed

        new Frame_Calander(0);
    }//GEN-LAST:event_FrameCall_CalanderActionPerformed

    private void Tf_IndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_IndexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_IndexActionPerformed

    private void Tf_AllMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_AllMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_AllMoneyActionPerformed

    private void Tf_PresentMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_PresentMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_PresentMoneyActionPerformed

    private void Tf_NotPaymoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_NotPaymoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_NotPaymoneyActionPerformed

    private void CB_SortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_SortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_SortActionPerformed

    private void TF_OldStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_OldStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_OldStudentActionPerformed

    private void TF_NewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_NewStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_NewStudentActionPerformed

    private void TF_AllStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_AllStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_AllStudentActionPerformed

    private void TF_EventDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_EventDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_EventDateActionPerformed

    private void TF_EventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_EventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_EventNameActionPerformed

    private void TF_AverageMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_AverageMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_AverageMoneyActionPerformed

    public Vector getColumn_MemberTable() {
        Vector col = new Vector();

        System.out.println(MemberTable.getColumnCount());

        for (int i = 0; i < MemberTable.getColumnCount(); i++) {
            col.add(MemberTable.getColumnName(i));

        }
        return col;
    }

    public Vector getColumn_MsfTable() {
        Vector col = new Vector();

        for (int i = 0; i < MsfTable.getColumnCount(); i++) {
            col.add(MsfTable.getColumnName(i));

        }

        return col;
    }

    public void tableRefresh_MemberTable() {

        MemberDAO dao = new MemberDAO();
        DefaultTableModel model = new DefaultTableModel(dao.getMemberList(), getColumn_MemberTable());
        MemberTable.setModel(model);

    }
    
     public void tableRefresh_MsfTable() {

        MemberDAO dao = new MemberDAO();
        DefaultTableModel model = new DefaultTableModel(dao.getMemberList(), getColumn_MsfTable());
        MsfTable.setModel(model);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame f = new MainFrame();

                f.setTitle("회비관리 프로그램");
                f.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Delete_Mem;
    private javax.swing.JButton Btn_Delete_Mfs;
    private javax.swing.JButton Btn_Enter_Mem;
    private javax.swing.JButton Btn_Enter_Mfs;
    private javax.swing.JButton Btn_Reset_Mem;
    private javax.swing.JButton Btn_Reset_Mfs;
    private javax.swing.JButton Btn_Update_Mem;
    private javax.swing.JButton Btn_Update_Mfs;
    private javax.swing.JComboBox<String> CB_Sort;
    private javax.swing.JTable EventTable;
    private javax.swing.JButton FrameCall_Calander;
    private javax.swing.JButton FrameCall_Member;
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JTable MemberTable;
    private javax.swing.JTable MsfTable;
    private javax.swing.JPanel Panel_EventManager;
    private javax.swing.JPanel Panel_MemberManager;
    private javax.swing.JPanel Panel_PayManager;
    private javax.swing.JTextField TF_AllStudent;
    private javax.swing.JTextField TF_AverageMoney;
    private javax.swing.JTextField TF_EventDate;
    private javax.swing.JTextField TF_EventName;
    private javax.swing.JTextField TF_NewStudent;
    private javax.swing.JTextField TF_OldStudent;
    private javax.swing.JTextField TF_StudentId;
    private javax.swing.JTextField Tf_AllMoney;
    public static javax.swing.JTextField Tf_Date;
    private javax.swing.JTextField Tf_Department;
    private javax.swing.JTextField Tf_Event;
    private javax.swing.JTextField Tf_Index;
    private javax.swing.JTextField Tf_Name;
    private javax.swing.JTextField Tf_Name_Mem;
    private javax.swing.JTextField Tf_NotPaymoney;
    private javax.swing.JTextField Tf_Payment;
    private javax.swing.JTextField Tf_Phone;
    private javax.swing.JTextField Tf_PresentMoney;
    private javax.swing.JTextField Tf_Price;
    private javax.swing.JTextField Tf_Remarks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    public static void setTf_Date(String str) {
        MainFrame.Tf_Date.setText(str);
    }

}
